REFRESH MATERIALIZED VIEW CONCURRENTLY mv_total_content_count;
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_total_size;
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_total_api_keys;
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_content_signature_meta;



